# Generated by Django 3.0 on 2022-05-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_fetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api_fetch.Brand'),
        ),
    ]
